// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgccmxpdccwikgujbloo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnY2NteHBkY2N3aWtndWpibG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzg2MjMsImV4cCI6MjA3MTcxNDYyM30.DeQoOqpA9F2Xft5B-U7ucO38CZBYJKnaRxmumnEWaj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});