// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahyrwkzgpcmlyekzsnbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeXJ3a3pncGNtbHlla3pzbmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzgxODMsImV4cCI6MjA3MDUxNDE4M30.G0ftDJ0wFrqYjRHH92u0nlnI6x_M7fRyKMD2go4CY_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});